// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yupqdfxyugilqiudplic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cHFkZnh5dWdpbHFpdWRwbGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTQyMzcsImV4cCI6MjA2NzEzMDIzN30.y1t24_2ocFWuTi_E3UyzGmeZWJzqY1jruexKAgWse4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});